project_id = "mighty"
[api]
enabled = true
schemas = ["public", "graphql_public"]
[auth]
enabled = true
enable_signup = false
site_url = "http://127.0.0.1:5173/"
additional_redirect_urls = ["http://127.0.0.1:5173", "http://127.0.0.1:5173/", "http://localhost:5173/", "https://riteshmitsloan.github.io/mighty/"]
[auth.email]
enable_signup = false
enable_confirmations = true
[functions.ai-gateway]
verify_jwt = false
