import{goalFit}from'./scoring.js';import{initialSelection,toggleSelection}from'./selection.js';import type{PageSnapshot,Profile,SaveInput}from'./types.js';
const body=document.querySelector('#content')!,account=document.querySelector('#account')!,notice=document.querySelector('#notice')! as HTMLElement,saveButton=document.querySelector('#save')! as HTMLButtonElement;
let state:PageSnapshot|null=null,userId:string|null=null,strategy='',connected=false,selected=new Set<string>(),saving=false,readGeneration=0;const operations=new Map<string,SaveInput>();
function el<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string,cls?:string){const node=document.createElement(tag);if(text)node.textContent=text;if(cls)node.className=cls;return node;}
async function send(message:unknown){try{const reply=await chrome.runtime.sendMessage(message);if(!reply?.ok)throw Error(reply?.message||'The extension did not respond.');return reply;}catch(e){throw Error(e instanceof Error?e.message:'The extension was reloaded. Close and reopen it to reconnect.');}}
function report(message:string){notice.textContent=message;}
function updateSave(){saveButton.disabled=saving||!connected||!state||(state.kind==='profile'?!(state.profile?.profileReadAt||(state.profile?.truncated&&state.profile.anchors.length)):state.kind==='search'?!selected.size:true);}
function render(){body.replaceChildren();if(!state){body.append(el('p','Reading the current tab…'));updateSave();return;}body.append(el('p',state.message,'hint'));
 if(state.kind==='profile'&&state.profile){const p=state.profile;body.append(el('h1',p.name));const fit=goalFit(strategy,p);body.append(el('p',fit.reason,'reason'),el('span',fit.label,'fit-label'));
 if(p.truncated)body.append(el('p','The full rendered profile exceeds the save limit. Nothing will be silently shortened or saved as complete.','warning'));
 const timing=p.anchors.filter(anchor=>anchor.kind==='timing'),timingCard=el('section');timingCard.append(el('h2','Timing signals'));
 if(timing.length)for(const anchor of timing)timingCard.append(el('p',anchor.text));else timingCard.append(el('p','No dated activity or role timing was visible in this read.','hint'));body.append(timingCard);
 const list=el('div');for(const anchor of p.anchors.filter(anchor=>anchor.kind!=='timing')){const item=el('section');item.append(el('h2',anchor.kind),el('p',anchor.text));list.append(item);}body.append(list);
 if(p.missingSections?.length)body.append(el('p','Not visible in this read: '+p.missingSections.join(', ')+'.','hint'));}
 if(state.kind==='search'){const list=el('div');for(const result of state.results){const row=el('label',undefined,'result'),check=el('input');check.type='checkbox';check.checked=selected.has(result.profileUrl);check.setAttribute('aria-label','Select '+result.name);check.addEventListener('change',()=>{const next=toggleSelection(selected,result.profileUrl,check.checked);selected=next.selected;check.checked=selected.has(result.profileUrl);report(next.message);updateSave();});const copy=el('div'),link=el('a',result.name);link.href=result.profileUrl;link.target='_blank';link.rel='noopener noreferrer';copy.append(link,el('p',result.subtitle||'Profile context has not been read.'));if(result.truncated)copy.append(el('p','Search text is incomplete. Open the actual profile to read its context.','warning'));row.append(check,copy);list.append(row);}body.append(list);if(state.results.length)body.append(el('p','All rendered results are shown. Only checked people will be saved.','hint'));}
 updateSave();
}
async function refresh(){const generation=++readGeneration;try{const[status,read]=await Promise.all([send({type:'mighty:status'}),send({type:'mighty:read_active'})]);if(generation!==readGeneration)return;
 if(userId!==status.userId){operations.clear();selected.clear();}userId=status.userId;strategy=status.strategy;connected=status.connected;account.replaceChildren(el('span',connected?'Account connected':'Account not connected'));if(!connected){const link=el('a','Open the app');link.href=status.appOrigin;link.target='_blank';link.rel='noopener noreferrer';account.append(link);}
 const previous=state;state=read.snapshot;if(state?.kind==='search'){const changed=previous?.kind!=='search'||previous.pageUrl!==state.pageUrl;if(changed)selected=initialSelection(state.results);else{const visible=new Set(state.results.map(x=>x.profileUrl));selected=new Set([...selected].filter(x=>visible.has(x)));}}render();
 }catch(e){connected=false;report((e as Error).message);updateSave();}}
saveButton.addEventListener('click',async()=>{if(!state||!connected||!userId)return;saving=true;updateSave();report('Saving…');const profiles:Profile[]=state.kind==='profile'&&state.profile?[state.profile]:state.kind==='search'?state.results.filter(x=>selected.has(x.profileUrl)).map(x=>({profileUrl:x.profileUrl,name:x.name,anchors:[],profileReadAt:null,truncated:x.truncated,truncationReasons:x.truncated?['search_text_limit']:[]})):[];
 const source=state.kind==='profile'?'rendered_profile':'search_result';const owner=userId;const results=await Promise.allSettled(profiles.map(async profile=>{const key=owner+'|'+profile.profileUrl+'|'+source;let request=operations.get(key);if(!request){request={operationId:crypto.randomUUID(),userId:owner,profile,source};operations.set(key,request);}await send({type:'mighty:save',save:request});operations.delete(key);return profile.profileUrl;}));
 const saved=results.filter(x=>x.status==='fulfilled').length;for(const result of results)if(result.status==='fulfilled')selected.delete(result.value);const failure=results.find(x=>x.status==='rejected') as PromiseRejectedResult|undefined;report(failure?String(failure.reason?.message||'A save is still pending.'):saved===1?'Saved to your account inbox.':'Selected people saved to your account inbox.');saving=false;render();});
document.querySelector('#skip')!.addEventListener('click',()=>window.close());
let reconnect:ReturnType<typeof setTimeout>|undefined;
function connect(){try{const port=chrome.runtime.connect({name:'mighty:popup'});port.onMessage.addListener(()=>{if(!saving)void refresh();});port.onDisconnect.addListener(()=>{connected=false;updateSave();clearTimeout(reconnect);reconnect=setTimeout(()=>{connect();void refresh();},100);});}catch{report('The extension was reloaded. Reopen it to reconnect.');}}
addEventListener('focus',()=>void refresh());connect();void refresh();
