import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',P='33333333-3333-4333-8333-333333333333';
test('all migrations apply and database security/budgets enforce the brief',async t=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;grant usage on schema storage to authenticated;grant all on storage.objects to authenticated;`);
 for(const name of ['001_schema.sql','002_ai.sql','003_quota.sql'])await db.exec(await readFile(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));
 await db.exec(`insert into auth.users values('${A}'),('${B}');insert into public.users(user_id) values('${A}'),('${B}');insert into public.settings(user_id) values('${A}'),('${B}');insert into public.ai_user_limits(user_id) values('${A}'),('${B}');insert into public.outreach_log(id,user_id,person) values('${P}','${B}','Isolated test record');update public.ai_config set enabled=true;`);
 await t.test('every table has RLS; anonymous reads empty and writes return 42501',async()=>{const r=await db.query<any>(`select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and not c.relrowsecurity;`);assert.equal(r.rows.length,0);await db.exec('set role anon');assert.equal((await db.query('select * from public.outreach_log')).rows.length,0);await assert.rejects(db.query(`insert into public.outreach_log(user_id,person) values('${A}','refused')`),(e:any)=>e.code==='42501');await db.exec('reset role');});
 await t.test('cross-account reads/writes/references and entitlement changes fail',async()=>{await db.exec(`set role authenticated;set request.jwt.claim.sub='${A}';`);assert.equal((await db.query('select * from public.outreach_log')).rows.length,0);await assert.rejects(db.query(`insert into public.outreach_log(user_id,person) values('${B}','refused')`),(e:any)=>e.code==='42501');await assert.rejects(db.query(`insert into public.outreach_events(user_id,relationship_id,kind,body) values('${A}','${P}','note','refused')`),(e:any)=>e.code==='23503');await assert.rejects(db.query(`update public.users set account_status='active'`),(e:any)=>e.code==='42501');await assert.rejects(db.query(`update public.settings set plan_caps='{"unlimited":true}'`),(e:any)=>e.code==='42501');await db.exec('reset role');});
 await t.test('private archive paths are isolated and no bucket is public',async()=>{await db.exec(`insert into storage.objects(bucket_id,name) values('archives','${B}/archive.zip');set role authenticated;set request.jwt.claim.sub='${A}';`);assert.equal((await db.query('select * from storage.objects')).rows.length,0);await assert.rejects(db.query(`insert into storage.objects(bucket_id,name) values('archives','${B}/other.zip')`),(e:any)=>e.code==='42501');await db.exec(`insert into storage.objects(bucket_id,name) values('archives','${A}/own.zip');reset role;`);assert.equal((await db.query<any>('select public from storage.buckets')).rows[0].public,false);});
 await t.test('fact history is immutable and kept promises must reference promises',async()=>{await db.exec(`insert into public.outreach_events(user_id,relationship_id,kind,body) values('${B}','${P}','note','A test-only note');`);await assert.rejects(db.exec('update public.outreach_events set body=\'changed\''),(e:any)=>e.code==='42501');await assert.rejects(db.exec('delete from public.outreach_events'),(e:any)=>e.code==='42501');await assert.rejects(db.exec(`insert into public.outreach_events(user_id,relationship_id,kind,related_event_id) select user_id,relationship_id,'promise_kept',id from public.outreach_events`),(e:any)=>e.code==='23514');});
 await t.test('AI configuration and privileged functions remain service-only',async()=>{await db.exec('set role anon');await assert.rejects(db.query('select * from public.ai_config'),(e:any)=>e.code==='42501');await assert.rejects(db.query(`select public.ai_precheck('${A}','profile_briefing')`),(e:any)=>e.code==='42501');await db.exec('reset role');const r=await db.query<any>(`select has_function_privilege('service_role','public.ai_reserve_call(text,uuid,uuid,integer)','execute') as allowed`);assert.equal(r.rows[0].allowed,true);});
 await t.test('pending calls consume daily cap; a duplicate cannot dispatch twice',async()=>{await db.exec(`update public.ai_user_limits set daily_cap=1 where user_id='${A}';`);const id=crypto.randomUUID();await db.query(`select public.ai_reserve_call('profile_briefing','${A}','${id}')`);await assert.rejects(db.query(`select public.ai_reserve_call('profile_briefing','${A}','${id}')`),(e:any)=>e.code==='23505');await assert.rejects(db.query(`select public.ai_reserve_call('profile_briefing','${A}')`),/Daily Assist limit/);await db.query(`select public.ai_release_call('${id}')`);assert.equal((await db.query('select * from public.ai_call_log')).rows.length,0);await db.exec(`update public.ai_user_limits set daily_cap=20`);});
 await t.test('monthly and project-wide dollar budgets include pending reservations',async()=>{await db.exec(`update public.ai_user_limits set monthly_usd_ceiling=0 where user_id='${A}';`);await assert.rejects(db.query(`select public.ai_reserve_call('profile_briefing','${A}')`),/Monthly cost ceiling/);await db.exec(`update public.ai_user_limits set monthly_usd_ceiling=5;update public.ai_company_budget set daily_usd_ceiling=0;`);await assert.rejects(db.query(`select public.ai_reserve_call('profile_briefing','${A}')`),/Daily company budget/);await db.exec('update public.ai_company_budget set daily_usd_ceiling=10');});
 await t.test('real usage rates confirm once and uncertain dispatch is never refunded',async()=>{const id=crypto.randomUUID();await db.query(`select public.ai_reserve_call('profile_briefing','${A}','${id}')`);await db.exec(`update public.ai_call_log set dispatched_at=now() where id='${id}'`);assert.equal((await db.query<any>(`select public.ai_release_call('${id}') as released`)).rows[0].released,false);await assert.rejects(db.query(`select public.ai_confirm_call('${id}',1000,400,0)`),/Cost does not match/);assert.equal((await db.query<any>(`select public.ai_confirm_call('${id}',1000,400,0.00525) as ok`)).rows[0].ok,true);assert.equal((await db.query<any>(`select public.ai_confirm_call('${id}',1000,400,0.00525) as ok`)).rows[0].ok,false);const r=(await db.query<any>('select pending,tokens_in,tokens_out,cost_usd from public.ai_call_log')).rows[0];assert.equal(r.pending,false);assert.equal(Number(r.cost_usd),.00525);});
 await t.test('flat search cap admits exactly three and refuses the fourth',async()=>{await db.exec('update public.people_search_config set daily_cap=3');const r=[];for(let i=0;i<4;i++)r.push((await db.query<any>('select public.claim_people_search() as result')).rows[0].result);assert.deepEqual(r.map(x=>x.allowed),[true,true,true,false]);assert.deepEqual(r.map(x=>x.remaining),[2,1,0,0]);});
 await t.test('lapsed accounts keep records and cannot mutate them',async()=>{await db.exec(`update public.users set account_status='lapsed' where user_id='${B}';set role authenticated;set request.jwt.claim.sub='${B}';`);assert.equal((await db.query('select * from public.outreach_log')).rows.length,1);await assert.rejects(db.query(`insert into public.outreach_events(user_id,relationship_id,kind,body) values('${B}','${P}','note','refused')`),(e:any)=>e.code==='42501');await db.exec('reset role');});
 await db.close();
});
