import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{createRequire}from'node:module';import{resolve}from'node:path';import{fileURLToPath}from'node:url';
import {mightyAppLink} from '../src/app-link.js';
import{readProfile,readSearchResults,classifySearchPage,snapshot,blockedState,recentRoleStart,hasSubstantiveProfile}from'../src/profile.js';import{canonicalProfileURL,exactOrigin}from'../src/urls.js';import{goalFit,canRequestBrief}from'../src/scoring.js';import{initialSelection,toggleSelection}from'../src/selection.js';import{parseExternalMessage,isExternalSender,sessionFromVerifiedToken,validateSave,inboxPayload,matchingPending,pendingKey}from'../src/messaging.js';import type{Profile,Session}from'../src/types.js';
const deps=process.env.MIGHTY_DEPS_ROOT||fileURLToPath(new URL('../../',import.meta.url));const{parseHTML}=createRequire(resolve(deps,'package.json'))('linkedom');
const documentOf=(html:string)=>parseHTML(html).document as Document;const fixture=(name:string)=>documentOf(readFileSync(new URL('./fixtures/'+name,import.meta.url),'utf8'));
const profileUrl='https://www.linkedin.com/in/jordan-rivers/',searchUrl='https://www.linkedin.com/search/results/people/?keywords=healthcare',now='2026-09-12T12:00:00.000Z';
const rich=()=>readProfile(fixture('profile-rich.html'),profileUrl,now)!;
const uid='12345678-1234-4234-9234-123456789abc',other='22345678-1234-4234-9234-123456789abc',operationId='32345678-1234-4234-9234-123456789abc';
const s:Session={userId:uid,accessToken:'test-only',expiresAt:Date.parse(now)+100000,strategy:'Healthcare leaders'};
test('pairing links preserve hosted and loopback app bases without carrying account data',()=>{
 const id='b'.repeat(32);
 for(const [base,expected] of [['https://riteshmitsloan.github.io/mighty/','https://riteshmitsloan.github.io/mighty/'],['http://localhost:5173','http://localhost:5173/'],['http://127.0.0.1:5173/','http://127.0.0.1:5173/']]){
  assert.equal(mightyAppLink(base,id,false),expected+'?mighty_extension='+id+'#connect-extension');
  assert.equal(mightyAppLink(base,id,true),expected);
 }
});
test('pairing links reject invalid IDs and unsafe or credential-bearing app addresses',()=>{
 for(const id of ['', 'a'.repeat(31), 'q'.repeat(32), 'a'.repeat(32)+'&token=private'])assert.throws(()=>mightyAppLink('http://localhost:5173',id,false),/identifier/);
 for(const url of ['javascript:alert(1)','http://example.com/','https://user:password@example.com/','https://example.com/?access_token=private','https://example.com/#access_token=private'])assert.throws(()=>mightyAppLink(url,'a'.repeat(32),false),/address/);
});
test('rich rendered profile captures every required anchor kind and actual timing',()=>{const p=rich();assert.equal(p.name,'Jordan Rivers');assert.equal(p.profileReadAt,now);for(const kind of['headline','location','about','experience','education','skills','languages','certifications','timing'])assert.ok(p.anchors.some(a=>a.kind===kind),kind);assert.ok(p.anchors.some(a=>a.kind==='timing'&&a.text==='Jan 2023 – Present'));assert.ok(p.anchors.every(a=>a.sourceUrl.startsWith(profileUrl+'#')));assert.equal(p.truncated,false);});
test('hidden text, recommendations, and scripts never become profile evidence',()=>{const text=JSON.stringify(rich());for(const excluded of['Secret hidden','Accessibility duplicate','Investment banking','Invented data','Wrong Person'])assert.ok(!text.includes(excluded),excluded);});
test('nested experience lists do not create duplicate top-level anchors',()=>{const p=rich();assert.equal(p.anchors.filter(x=>x.kind==='experience').length,2);assert.ok(p.anchors.some(x=>x.kind==='experience'&&x.text.includes('Healthcare interoperability')));});
test('missing rich context is unknown and cannot support a brief',()=>{const doc=documentOf('<main><section><h1>A Person</h1></section></main>');const p=readProfile(doc,profileUrl,now);assert.equal(p?.profileReadAt,null);assert.equal(canRequestBrief(p),false);assert.equal(snapshot(doc,profileUrl).state,'unknown');assert.equal(readProfile(documentOf('<main><h2>Nothing loaded</h2></main>'),profileUrl),null);});
test('long rendered anchors remain intact below the whole-snapshot limit',()=>{const headline='healthcare '.repeat(200).trim(),about='Evidence sentence. '.repeat(200).trim();const p=readProfile(documentOf('<main><section><h1>A Person</h1><div data-field="headline">'+headline+'</div></section><section><h2>About</h2><p>'+about+'</p></section></main>'),profileUrl,now)!;assert.equal(p.truncated,false);assert.equal(p.anchors.find(a=>a.kind==='headline')?.text,headline);assert.equal(p.anchors.find(a=>a.kind==='about')?.text,'About '+about);assert.equal(canRequestBrief(p),true);assert.doesNotThrow(()=>validateSave({userId:uid,operationId,profile:p,source:'rendered_profile'},s));});
test('local matcher explains explicit goal evidence and never emits a numerical score',()=>{const match=goalFit('Meet healthcare engineering leaders',rich());assert.equal(match.label,'Goal overlap');assert.match(match.reason,/strategy mentions/);assert.ok(match.evidence.length);assert.ok(!('score'in match));assert.ok(!('percentile'in match));assert.equal(goalFit('Investment banking',rich()).label,'No clear goal overlap');assert.equal(goalFit('',rich()).label,'Not enough context');});
test('search snippets never become profile reads or briefs',()=>{const rows=readSearchResults(fixture('search-seven.html'),searchUrl);assert.equal(rows.length,7);assert.ok(rows.every(x=>x.profileReadAt===null));assert.equal(readProfile(fixture('search-seven.html'),searchUrl),null);assert.equal(canRequestBrief({...rich(),profileReadAt:null}),false);});
test('all seven rendered results stay visible with only first five selected',()=>{const rows=readSearchResults(fixture('search-seven.html'),searchUrl);const selected=initialSelection(rows);assert.deepEqual([...selected],rows.slice(0,5).map(x=>x.profileUrl));assert.equal(selected.has(rows[5].profileUrl),false);assert.equal(selected.has(rows[6].profileUrl),false);const refused=toggleSelection(selected,rows[5].profileUrl,true);assert.equal(refused.selected.size,5);assert.ok(refused.message);const removed=toggleSelection(selected,rows[0].profileUrl,false);assert.equal(toggleSelection(removed.selected,rows[5].profileUrl,true).selected.size,5);});
test('HTTP 200 blocked, explicit empty, and ambiguous missing results stay distinct',()=>{assert.equal(classifySearchPage(fixture('search-blocked-200.html'),searchUrl,200).state,'blocked');assert.equal(classifySearchPage(fixture('search-empty-200.html'),searchUrl,200).state,'empty');assert.equal(classifySearchPage(fixture('search-unknown-200.html'),searchUrl,200).state,'unknown');assert.equal(classifySearchPage(fixture('search-seven.html'),searchUrl,200).state,'ready');});
test('login redirect and 403/429 are not interpreted as successful empty searches',()=>{assert.equal(blockedState(documentOf('<main><h1>Sign in</h1></main>'),searchUrl),'auth_required');assert.equal(blockedState(fixture('search-seven.html'),'https://www.linkedin.com/authwall?x=1'),'auth_required');assert.equal(classifySearchPage(fixture('search-seven.html'),searchUrl,429).state,'blocked');assert.equal(classifySearchPage(fixture('search-seven.html'),searchUrl,503).state,'unknown');});
test('URL canonicalization removes tracking and rejects hostile or non-profile targets',()=>{assert.equal(canonicalProfileURL('https://linkedin.com/in/Jordan-Rivers?trk=test#about'),profileUrl);assert.equal(canonicalProfileURL('/in/jordan-rivers/'),profileUrl);for(const bad of['https://linkedin.com.evil.test/in/x/','https://evil.test/in/x/','http://linkedin.com/in/x/','https://user@linkedin.com/in/x/','https://linkedin.com/in/a%2Fb/','https://linkedin.com/in/%ZZ/','https://linkedin.com/mynetwork/invite-connect/connections/','javascript:alert(1)'])assert.equal(canonicalProfileURL(bad),null,bad);});
test('bridge requires exact origins, including the configured local development port',()=>{const allowed=['http://127.0.0.1:5173','https://mighty.example.com'];assert.equal(isExternalSender({url:'http://127.0.0.1:5173/'},allowed),true);assert.equal(isExternalSender({url:'http://127.0.0.1:5174/'},allowed),false);assert.equal(isExternalSender({url:'https://mighty.example.com/path',origin:'https://mighty.example.com'},allowed),true);assert.equal(isExternalSender({url:'https://mighty.example.com.evil.test/'},allowed),false);assert.equal(isExternalSender({url:'https://mighty.example.com/',id:'another-extension'},allowed),false);assert.equal(exactOrigin('https://mighty.example.com@evil.test','https://mighty.example.com'),false);});
test('hosted bridge is scoped to Mighty directory and ties sender origin to its actual URL',()=>{
 const hosted='https://riteshmitsloan.github.io',allowed=[hosted+'/mighty/','http://localhost:5173/'];
 for(const path of ['/mighty/','/mighty/index.html','/mighty/?code=fixture#section'])assert.equal(isExternalSender({url:hosted+path,origin:hosted},allowed),true,path);
 for(const url of [hosted+'/',hosted+'/another-repo/',hosted+'/mighty-other/',hosted+'/other/mighty/',hosted+'/mighty/../another-repo/',hosted+'/mighty/%2e%2e/another-repo/',hosted+'/mighty/%2f../another-repo/',hosted+':444/mighty/','https://someoneelse.github.io/mighty/','https://riteshmitsloan.github.io.evil.test/mighty/','https://user@riteshmitsloan.github.io/mighty/'])assert.equal(isExternalSender({url},allowed),false,url);
 assert.equal(isExternalSender({url:hosted+'/mighty/',origin:'http://localhost:5173'},allowed),false);
 assert.equal(isExternalSender({url:hosted+'/mighty/',origin:'null'},allowed),false);
});
test('bridge rejects refresh tokens, unknown fields and message types',()=>{assert.deepEqual(parseExternalMessage({type:'mighty:connect',protocol:1,accessToken:'session'}),{type:'connect',accessToken:'session'});for(const v of[{type:'mighty:connect',protocol:1,accessToken:'session',refreshToken:'secret'},{type:'fetch',protocol:1,url:'https://evil.test'},{type:'mighty:connect',protocol:2,accessToken:'x'},[]])assert.throws(()=>parseExternalMessage(v));});
function token(sub:string,exp:number,iss='https://project.supabase.co/auth/v1'){return'b64.'+Buffer.from(JSON.stringify({sub,exp,iss})).toString('base64url')+'.signature';}
test('verified handoff binds subject, issuer and short expiration',()=>{const time=Date.parse(now),exp=time/1000+1800;assert.equal(sessionFromVerifiedToken(token(uid,exp),uid,'https://project.supabase.co',time).userId,uid);assert.throws(()=>sessionFromVerifiedToken(token(other,exp),uid,'https://project.supabase.co',time));assert.throws(()=>sessionFromVerifiedToken(token(uid,exp,'https://evil.test/auth/v1'),uid,'https://project.supabase.co',time));assert.throws(()=>sessionFromVerifiedToken(token(uid,time/1000-1),uid,'https://project.supabase.co',time));assert.throws(()=>sessionFromVerifiedToken(token(uid,time/1000+86400),uid,'https://project.supabase.co',time));});
test('save contract is bound to verified account and preserves one idempotency key',()=>{const saved=validateSave({userId:uid,operationId,profile:rich(),source:'rendered_profile'},s);const payload=inboxPayload(saved);assert.equal(payload.operation_id,operationId);assert.equal(payload.user_id,uid);assert.equal(payload.profile_read_at,now);assert.equal(pendingKey(saved),'pending:'+uid+':'+operationId);assert.throws(()=>validateSave({...saved,userId:other},s));});
test('search saves cannot claim rendered anchors or a profile read',()=>{const profile:Profile={profileUrl,name:'A Person',anchors:[],profileReadAt:null,truncated:false,truncationReasons:[]};assert.equal(validateSave({userId:uid,operationId,profile,source:'search_result'},s).profile.profileReadAt,null);assert.throws(()=>validateSave({userId:uid,operationId,profile:rich(),source:'search_result'},s));});
test('queued account A saves are never drained under account B',()=>{const row={userId:uid,operationId,profile:rich(),source:'rendered_profile' as const,queuedAt:now};assert.equal(matchingPending([row],s).length,1);assert.equal(matchingPending([row],{...s,userId:other}).length,0);});
test('partial real reads preserve anchors but never send a profile_read_at',()=>{const profile={...rich(),truncated:true,truncationReasons:['anchor_text_limit'],profileReadAt:null};const save=validateSave({userId:uid,operationId,profile,source:'rendered_profile'},s);const payload=inboxPayload(save);assert.equal(payload.profile_read_at,null);assert.equal(payload.snapshot.profileReadAt,null);assert.equal(payload.snapshot.source,'rendered_profile');assert.ok(payload.snapshot.anchors.length);assert.ok(!('source'in payload));assert.ok(!('profile_snapshot'in payload));});
test('more than sixteen section items and forty anchors are all preserved',()=>{const items=Array.from({length:55},(_,i)=>'<li>Skill item '+i+'</li>').join('');const p=readProfile(documentOf('<main><section><h1>Person</h1><div data-field="headline">Healthcare engineer</div></section><section><h2>Skills</h2><ul>'+items+'</ul></section></main>'),profileUrl,now)!;assert.equal(p.truncated,false);assert.equal(p.anchors.filter(a=>a.kind==='skills').length,55);assert.ok(p.anchors.some(a=>a.text==='Skill item 54'));assert.equal(p.profileReadAt,now);assert.equal(canRequestBrief(p),true);assert.doesNotThrow(()=>validateSave({userId:uid,operationId,profile:p,source:'rendered_profile'},s));});
test('long search fields are explicitly incomplete instead of silently clipped',()=>{const results=readSearchResults(documentOf('<main><li><h3><a href="/in/long-name/">'+'Long '.repeat(80)+'</a></h3></li></main>'),searchUrl);assert.equal(results.length,1);assert.equal(results[0].truncated,true);assert.equal(results[0].profileReadAt,null);});
test('headline-only saves remain incomplete and empty section labels never unlock a brief',()=>{
 for(const extra of['','<section><h2>Experience</h2></section>','<section><h2>Skills</h2><a>Show all skills</a></section>']){
  const p=readProfile(documentOf('<main><section><h1>A Person</h1><div data-field="headline">Healthcare engineer</div></section>'+extra+'</main>'),profileUrl,now)!;
  assert.equal(p.profileReadAt,null);assert.equal(hasSubstantiveProfile(p),false);assert.equal(canRequestBrief(p),false);assert.equal(goalFit('healthcare',p).label,'Not enough context');
  const saved=validateSave({userId:uid,operationId,profile:p,source:'rendered_profile'},s);
  assert.equal(saved.profile.profileReadAt,null);assert.equal(saved.profile.anchors.length,1);assert.equal(saved.profile.anchors[0].kind,'headline');
  assert.equal(canRequestBrief({...p,profileReadAt:now}),false);assert.throws(()=>validateSave({userId:uid,operationId,profile:{...p,profileReadAt:now},source:'rendered_profile'},s),/actual profile/);
 }
});
test('recent rendered posts and role starts have timing evidence; old and undated activity do not gain recency',()=>{
 const p=readProfile(fixture('profile-timing.html'),profileUrl,now)!;
 const activity=p.anchors.filter(a=>a.kind==='activity'),timing=p.anchors.filter(a=>a.kind==='timing');
 assert.equal(activity.length,3);assert.ok(activity.some(a=>a.text.includes('without a date')));assert.ok(!JSON.stringify(p).includes('Hidden recent post'));
 assert.equal(timing.filter(a=>a.text.startsWith('Recent rendered activity:')).length,1);assert.ok(timing.some(a=>a.text==='Recent rendered activity: 2d'));
 assert.equal(timing.filter(a=>a.text.startsWith('Recent role start')).length,1);assert.ok(timing.some(a=>a.text.includes('Jul 2026 – Present')));
 assert.ok(!timing.some(a=>a.text.startsWith('Recent')&&a.text.includes('2020')));assert.equal(p.profileReadAt,now);
 const saved=inboxPayload(validateSave({userId:uid,operationId,profile:p,source:'rendered_profile'},s));assert.deepEqual(saved.snapshot.anchors,p.anchors);
});
test('role recency uses explicit current-role dates and refuses ambiguous years, old dates and future dates',()=>{
 assert.equal(recentRoleStart('Jul 2026 – Present',now),true);assert.equal(recentRoleStart('September 2026 – Current',now),true);assert.equal(recentRoleStart('2026-08-15 – Present',now),true);
 for(const range of['2026 – Present','Jun 2026 – Present','Jan 2023 – Present','Oct 2026 – Present','Jul 2026 – Aug 2026','2026-02-30 – Present'])assert.equal(recentRoleStart(range,now),false,range);
});
test('activity timing requires a visible timestamp; body text, hidden timestamps and future dates do not create recent posts',()=>{
 const doc=documentOf('<main><section><h1>Person</h1><div data-field="headline">Engineer</div></section><section><h2>Activity</h2><article><p>We delivered in 2d and learned a lot.</p></article><article><p>Hidden date</p><time hidden datetime="2026-09-11">1d</time></article><article><p>Future date</p><time datetime="2026-10-01">Tomorrow</time></article><article><p>Real relative timestamp</p><span data-field="posted-at">2w • Edited</span></article><article><p>Ambiguous three months</p><span data-field="posted-at">3mo</span></article></section></main>');
 const p=readProfile(doc,profileUrl,now)!;assert.equal(p.anchors.filter(a=>a.kind==='activity').length,5);assert.deepEqual(p.anchors.filter(a=>a.kind==='timing'&&a.text.startsWith('Recent')).map(a=>a.text),['Recent rendered activity: 2w']);assert.ok(p.anchors.some(a=>a.kind==='timing'&&a.text.includes('2026-10-01')));
});
test('activity tabs and follower counts are not fabricated into posts or complete profile evidence',()=>{
 const doc=documentOf('<main><section><h1>Person</h1><div data-field="headline">Engineer</div></section><section><h2>Activity</h2><p>5,000 followers</p><ul><li><button>Posts</button></li><li><button>Comments</button></li></ul></section></main>');
 const p=readProfile(doc,profileUrl,now)!;assert.equal(p.anchors.filter(a=>a.kind==='activity').length,0);assert.equal(p.profileReadAt,null);assert.ok(p.missingSections?.includes('activity'));
});
test('oversized profiles retain their final evidence but refuse the whole save instead of shortening it',()=>{
 const text='Long evidence '.repeat(4200)+'FINAL_UNTRUNCATED_SENTINEL';
 const p=readProfile(documentOf('<main><section><h1>Person</h1><div data-field="headline">Engineer</div></section><section><h2>About</h2><p>'+text+'</p></section></main>'),profileUrl,now)!;
 assert.ok(p.anchors.some(a=>a.text.endsWith('FINAL_UNTRUNCATED_SENTINEL')));assert.ok(new TextEncoder().encode(JSON.stringify(p)).byteLength>49152);assert.equal(p.truncated,true);assert.ok(p.truncationReasons.includes('snapshot_size_limit'));assert.equal(p.profileReadAt,null);assert.equal(canRequestBrief(p),false);
 assert.throws(()=>validateSave({userId:uid,operationId,profile:p,source:'rendered_profile'},s),/snapshot size limit/);
});
test('whole-snapshot limit counts UTF-8 bytes rather than characters',()=>{
 const text='医'.repeat(18000)+'UTF8_END';const p=readProfile(documentOf('<main><section><h1>Person</h1></section><section><h2>About</h2><p>'+text+'</p></section></main>'),profileUrl,now)!;
 assert.ok(JSON.stringify(p).length<49152);assert.equal(p.truncated,true);assert.ok(p.anchors.some(a=>a.text.endsWith('UTF8_END')));assert.throws(()=>validateSave({userId:uid,operationId,profile:p,source:'rendered_profile'},s),/snapshot size limit/);
});
test('missing rendered fields stay explicit gaps rather than invented attributes',()=>{
 const p=readProfile(documentOf('<main><section><h1>Person</h1></section><section><h2>Skills</h2><ul><li>TypeScript</li></ul></section></main>'),profileUrl,now)!;
 assert.equal(p.profileReadAt,now);assert.ok(p.missingSections?.includes('location'));assert.ok(p.missingSections?.includes('experience'));assert.ok(p.missingSections?.includes('education'));assert.ok(!p.anchors.some(a=>a.kind==='location'));
});
test('older activity timestamps remain stored as facts without a recent-activity claim',()=>{const p=readProfile(fixture('profile-timing.html'),profileUrl,now)!;assert.ok(p.anchors.some(a=>a.kind==='timing'&&a.text==='Rendered activity timestamp: 1yr (2025-09-10T12:00:00Z)'));assert.ok(!p.anchors.some(a=>a.kind==='timing'&&a.text.startsWith('Recent')&&a.text.includes('2025-09-10')));});
